### ISSUE TITLE
IgnoreFields doesn't seem to work?

### ISSUE THREAD

**Issue by SVenky** [google/go-cmp#127]
Let me know if am doing something wrong here.

I tried ignorefields but it doesn't work.
struct is defined as below and trying to ignore the As field. xxx is the package in which the struct is defined.
type Neighbor struct {
	Address  string
	LocalAddress string
	As       uint32
}
cmpopts.IgnoreFields(xxx.Neighbor{}, "AS")

gives panic error.

github.com/google/go-cmp/cmp/cmpopts.newStructFilter(0x126daa0, 0xc0003fdb30, 0xc000641c38, 0x1, 0x1, 0xc000641a68, 0xc000641a68, 0x40b01f, 0x126daa0)
	go/src/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go:51 +0x2ff
github.com/google/go-cmp/cmp/cmpopts.IgnoreFields(0x126daa0, 0xc0003fdb30, 0xc000641c38, 0x1, 0x1, 0x98, 0x12043c0)
	go/src/github.com/google/go-cmp/cmp/cmpopts/ignore.go:25 +0x63

**Comment by dsnet** [comment]
In your struct, your field is name `As` (note the lower-case 's'), but you are calling `cmpopts.IgnoreFields` with `AS` (note the upper-case 'S'). Is there an accidental case-sensitivity issue going on here?

**Comment by SVenky** [comment]
Yes you are right :) Thanks for a quick reply!
