### ISSUE TITLE
invalid reflect.Value in compare reporter output

### ISSUE THREAD

**Issue by SVenky** [google/go-cmp#133]
When we compare two structures using the compare method and custom reporter. In some cases, it is returning back nil, 0 etc and in some cases returning invalid reflect.Value.

Do we know what case it could return invalid reflect.Value?

**Comment by SVenky** [comment]
Latest version.
API I am using:  cmp.Equal() with custom basic reporter one similar that given in example.
I am comparing 2 structure and see something like this.

.Peer[0x8]: -:\u003cinvalid reflect.Value\u003e, +:\u0026{Async:0xc00053bda0 FailureTransitions:0xc00054a0e8 LastFailureTime:\u003cnil\u003e LocalAddress:0xc000372490 LocalDiagnosticCode:1 LocalDiscriminator:0xc00054a238 OperState:2 RemoteAddress:0xc000373610 RemoteControlPlaneIndependent:0xc00054a400 RemoteDiagnosticCode:1 RemoteDiscriminator:0xc00054a560 RemoteMinimumReceiveInterval:0xc00054a600 RemoteSessionState:4 SessionState:4 SubscribedProtocols:0xc00037bdc0}"

**Comment by dsnet** [comment]
Ah. Take a look at [`cmp.PathStep.Values`](https://godoc.org/github.com/google/go-cmp/cmp#PathStep.Values). It mentions that the values may be invalid (or non-interfaceable) in the following situations:
* For StructField, both are not interface-able if the current field is unexported and the struct type is not explicitly permitted by AllowUnexported to traverse unexported fields.
* For SliceIndex, one may be invalid if an element is missing from either the x or y slice.
* For MapIndex, one may be invalid if an entry is missing from either the x or y map.

**Comment by dsnet** [comment]
Closing this as a resolved question.

**Comment by SVenky** [comment]
Thanks for pointing out... I missed that comment. Yes, it is a case map with different index.
