### ISSUE TITLE
check that some struct fully contains in another

### ISSUE THREAD

**Issue by vtolstov** [google/go-cmp#137]
i have example struct
type X struct {
  Name string
  Enabled bool
  Opts map[string]interface{}
}

and i have slice of such structs,
i need to get all structs that have for example Enabled: true in that slice. Does it possible with this package?
Now i have ugly reflect based variant.

**Comment by dsnet** [comment]
`cmp` is intended to be a comparison library, rather than a verification library.

Let's suppose you have variable which is a `[]X`, and you want to verify that the `Enabled` field is true for all elements. The best way to ensure that property is to set `Enabled` to true in the golden slice that you are comparing against.

**Comment by vtolstov** [comment]
my use-case different, i need to find all structs that have the same fields, but unitialized fields need to be skipped and not checked.

**Comment by dsnet** [comment]
I'm not sure I follow, is there a more substantial code example that you can show?

**Comment by vtolstov** [comment]
for example item definition
type LogicalSwitch struct {
  UUID string
  Name string
  ExternalIDs map[string]string
}

and i have slice of such items []*LogicalSwitch

Now i need to find in this slice all items that have Name = test and have in ExternalIDs key=val (map["key"] = "val")

So i can't do full compare, because items can have in ExternalIDs many more keys, but i need item that have my specific key and name.

Now i do:
```
func (odbi *ovndb) getRows(table string, row interface{}) ([]interface{}, error) {
        var rows []interface{}
        //odbi.cachemutex.RLock()
        //defer odbi.cachemutex.RUnlock()

        cacheTable, ok := odbi.cache2[table]
        if !ok {
                return nil, ErrorSchema
        }

        // direct get by UUID
        t := reflect.ValueOf(row).Elem()
        if v := t.FieldByName("UUID"); len(v.String()) > 0 {
                if tblrow, ok := cacheTable[v.String()]; ok {
                        rows = append(rows, tblrow)
                        return rows, nil
                }
                return nil, ErrorNotFound
        }

        for _, tblrow := range cacheTable {
                rowVal := reflect.ValueOf(row).Elem()
                tblVal := reflect.ValueOf(tblrow).Elem()
                for i := 0; i < rowVal.NumField(); i++ {
                        rowField := rowVal.Field(i)
                        if reflect.Zero(rowField.Type()) == rowField {
                                continue
                        }
                        tblField := tblVal.Field(i)
                        switch rowField.Type().Kind() {
                        case reflect.Map:
                                //                      r := cmp.Equal(row, tblrow)
                                //              log.Printf("ssss %#+v\n", r)
                                rowIter := rowField.MapRange()
                                tblIter := tblField.MapRange()
                                for rowIter.Next() {
                                        for tblIter.Next() {
                                                mrk := rowIter.Key()
                                                mrv := rowIter.Value()
                                                mtk := rowIter.Key()
                                                mtv := rowIter.Value()
                                                if mrk.Interface() != mtk.Interface() || mrv.Interface() != mtv.Interface() {
                                                        continue
                                                }
                                        }
                                }
                        default:
                                if rowField.Interface() != tblField.Interface() {
                                        continue
                                }
                        }
                }
               rows = append(rows, tblrow)  

        }

        if len(rows) == 0 {
                return nil, ErrorNotFound
        }

        return rows, nil


```

**Comment by vtolstov** [comment]
this part of code misses that original struct have map[interface{}]interface{} and not map[string]string, so my code does not have recursive to get nested map values.

**Comment by dsnet** [comment]
This functionality is going beyond what `cmp` was intended to do. With the right set of options you might be able to pull off what you want, but `cmp` won't be able to handle this use-case out of the box.
