### ISSUE TITLE
how to compare time.Time type?

### ISSUE THREAD

**Issue by falnyr** [google/go-cmp#139]
Hi, I have a package defining a custom type for `time` which is used in various structs. I am trying to use a custom comparer to see if the times are equal but if I cast to the original type to use the `time.Equals` function, I'm getting an error `cannot handle unexported field: {main.Foo}.Created.wall
consider using a custom Comparer; if you control the implementation of type, you can also consider AllowUnexported or cmpopts.IgnoreUnexported` - which is why I started writing a custom comparer in the first place.

How can I approach this? 

My code: https://gist.github.com/falnyr/4643f4b4a8c20975d5ddb67055f0f675

**Comment by dsnet** [comment]
It seems that you're not actually comparing a `time.Time`, but a `MyTime`, which happens to have the same memory layout as `time.Time`, but is not the same Go type (it doesn't even have the same methods).

You can do one of the following:
* Add an equal method to `MyTime`:
```go
func (t MyTime) Equal(u MyTime) bool {
    return time.Time(t).Equal(time.Time(u))
}
```
* Pass a custom `cmp.Comparer` to `cmp.Equal`:
```go
cmp.Comparer(func(x, y MyTime) bool {
    return time.Time(x).Equal(time.Time(y))
})
```

**Comment by falnyr** [comment]
Oh, so my mistake was creating a comparer for the parent type, not the actual types I was interested in. Thank you!
