### ISSUE TITLE
imports github.com/google/go-cmp/cmp/internal/diff: use of internal package github.com/google/go-cmp/cmp/internal/diff not allowed

### ISSUE THREAD

**Issue by mihai-chiorean** [google/go-cmp#140]
`imports github.com/google/go-cmp/cmp/internal/diff: use of internal package github.com/google/go-cmp/cmp/internal/diff not allowed`

when using `cmp.Diff`.

```
import (
    4     "context"
    5     "errors"
    6     "fmt"
    7     "net/http"
    8     "reflect"
    9     "strings"
   10     "testing"
   11
+  12     "github.com/google/go-cmp/cmp"
   13     "github.com/stretchr/testify/assert"
   14 )
```

This is in the GOPATH

**Comment by dsnet** [comment]
Hi, something seems wrong with your Go environment that is independent of this project.

It's hard to help without knowing things like:
* What Go version are you using?
* Is modules enabled?
* What is `GOPATH` set to?
* Where you invoke the go command from?

All of these things affect how the toolchain builds code and also affects the logic to enforce internal packages.

**Comment by mihai-chiorean** [comment]
absolutely. I should have added this.
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mihaichiorean/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mihaichiorean/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_n/nx7vkmvs32dd6vd3bq07dldr0000gn/T/go-build922289216=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
```
GOPATH /Users/mihaichiorean/Go
```
- Go modules are the... default for `1.12.5`. so I'm guessing off
- I invoked the command from the the go path. I'm using go-cmp in a _test.go file, so I ran `go test` in the exact path where the test file is.

**Comment by dsnet** [comment]
What's the exact directory that you are invoking `go test`? Are symlinks involved?

**Comment by mihai-chiorean** [comment]
`/Users/mihaichiorean/Go/src/github.com/InVisionApp/billing-api/dal/client` no symlink involved

Btw, thanks for being on this!!

**Comment by dsnet** [comment]
Did you ever figure this out? I'm reasonably convinced that this has nothing to do with `cmp` but something weird is going on with how to Go toolchain is building packages.

**Comment by mihai-chiorean** [comment]
> Did you ever figure this out? I'm reasonably convinced that this has nothing to do with `cmp` but something weird is going on with how to Go toolchain is building packages.

I haven't. I found other ways to achieve my goal, w/o cmp. I'll give it another try

**Comment by KrzysztofMadejski** [comment]
I'm using modules vendoring in one project. I needed to vendor all internal packages for this error to go away:
```
govendor add github.com/google/go-cmp/cmp/internal/diff
govendor add github.com/google/go-cmp/cmp/internal/function
govendor add github.com/google/go-cmp/cmp/internal/flags
govendor add github.com/google/go-cmp/cmp/internal/value
```

**Comment by dsnet** [comment]
This is almost certainly an environment setup issue with regard to Go modules and nothing actionable for this specific project to do.
