### ISSUE TITLE
cmpopts to ignore fields within slices?

### ISSUE THREAD

**Issue by mrkagelui** [google/go-cmp#143]
Hi all,

My struct looks like this:
```go
type info struct {
  Num int
  Slice []dbEntry
}
type dbEntry struct {
  ID int
  CreatedAt time.Time
  OtherInfo int
}
```
Is there a way within cmpopts to compare `info`, ignoring the `ID` and `CreatedAt` fields within its `Slice`?

**Comment by dsnet** [comment]
It seems that `cmpopts.IgnoreFields(info{}, "Slice")` does what you desire.

**Comment by mrkagelui** [comment]
@dsnet thank you for the reply, however I was wondering if there is one opt I could use like
```go
infoA := info{...}
infoB := info{...}
equal := cmp.Equal(infoA, infoB, cmpopt.SomeOpt(infoA, "Slice[].ID", "Slice[].CreatedAt")
```
I could, of course, and actually I have written my own comparer for this purpose, just wondering if such option is available or even feasible to implement

**Comment by dsnet** [comment]
The options in `cmpopts` are intended to be simple (and thus simple to document and explain). Something that can reach further down into the tree and cross map, slice, or pointer boundaries is starting to get a bit too complex for comfort. It possible we add an option for that or even extend `IgnoreFields` to do that in the future.

**Comment by mrkagelui** [comment]
I see, all right.
