### ISSUE TITLE
Reporter - embedded types

### ISSUE THREAD

**Issue by akakjs** [google/go-cmp#144]
Hi, I'm attempting to document changed field values between a struct and it's modified copy, and I want to get the field paths to match their location on a marshalled document (json & protobuf). However within the reporter I'm unable to reliably identify embedded type fields.

I have a forked implementation that copies the value of the Anonymous from reflect.StructField to cmp.StructField in the compareStruct and that seems to do the job with minimal modification. 

Would you consider making this (or a similar) change to support this usecase?

Thanks,

Ben

**Comment by dsnet** [comment]
I apologize, but I don't understand what you're trying to do. Do you have an example?

**Comment by akakjs** [comment]
Sorry I needed more coffee before I created this issue.

What I'm trying to do is create an audit history of user modifications to a business entity (represented by a struct). So after I saw the support for custom reporters in cmp.Diff I thought I'd compare the modified and original instances of the struct, and use a custom reporter to create the list of changes.

However I also don't want to expose the presence of any embedded types in the reported paths, so the path to each change matches the field location when serialised to JSON.

In code what I'm trying to do is something like this :

    type Name struct {
		FirstName string
		LastName string
	}
	
	type Human struct {
		Name
		Age int
	}
	
	Alice := Human{
		Age: 31,
		Name: Name{
			FirstName:"Alice",
			LastName: "Example",
		},
	}
	
	// Alice's evil twin
	Malice := Human{
		Age: 31,
		Name: Name{
			FirstName:"Malice",
			LastName: "Example",
		},
	}
	
	cmp.Diff(Alice, Malice, cmp.Reporter(exampleReporter))
	
	// currently in PushStep(PathStep) when the reporter visits the "Name" field and I have to
	// append that to the field path, and I end up with:
	// {
	//   {
	//     Path : "Name.FirstName"
	//     ...
	//   },
	// }
	
	// But if I knew the field in the PathStep was an embedded type field I could skip that PathStep, and get :
	// {
	//   {
	//     Path : "FirstName"
	//     ...
	//   },
	// }

**Comment by dsnet** [comment]
I see. For this use case, I don't think any modification is necessary.

> I have a forked implementation that copies the value of the Anonymous from reflect.StructField to cmp.StructField in the compareStruct and that seems to do the job with minimal modification.

Given the [`cmp.Path`](https://godoc.org/github.com/google/go-cmp/cmp#Path) where the `n`th step is a [`cmp.StructField`](https://godoc.org/github.com/google/go-cmp/cmp#StructField), you can obtain the original `reflect.StructField` from the type information held in the `n-1`th step.

Specifically:
```go
var p cmp.Path = ...
f, _ := p[n-1].Type().FieldByName(p[n].Name())
```

**Comment by dsnet** [comment]
Also, since `Reporter` doesn't provide you a `Path`, you can trivially re-construct it by push/popping the provided `PathSteps`. [See the example](https://github.com/google/go-cmp/blob/master/cmp/example_reporter_test.go).

**Comment by akakjs** [comment]
Thanks for the fast replies! And for taking the time to point me in the right direction, I'll give it a go.

**Comment by dsnet** [comment]
Glad it helped, I'm going to close this as resolved. Feel free to respond if you need more assistance.
