### ISSUE TITLE
Question: How do I apply a transformer to a child field of a struct depending on the value of another field in the struct?

### ISSUE THREAD

**Issue by F21** [google/go-cmp#146]
I have a data structure that looks like this:

```go
type Mystruct struct {
  DataType int
  Data []byte
}

type Container struct {
  SomeValue string
  Children []Mystruct
}
```
The bytes contained in `Data` must be unmarshalled and transformed depending on the value `DataType` holds.

I tried using a `FilterValue`:
```go
func mytransformer(in []bytes) AnotherConcreteType{
   ...
}

cmp.FilterValue(func(x,y Mystruct) bool {
  return x.DataType == somevalue && y.DataType == somevalue
}, cmpopts. AcyclicTransformer("mytransformer", mytransformer)),
```
I think (according to my understanding, it will attempt to apply the transfer from the `Mystruct` struct and will not attempt to apply it to the fields within `Mystruct`.

Is there any way to achieve this?

**Comment by dsnet** [comment]
> I think (according to my understanding, it will attempt to apply the transfer from the Mystruct struct and will not attempt to apply it to the fields within Mystruct.

You are correct that it will apply on `Mystruct`, which you can transform into something else entirely. The `cmpopts.AcyclicTransformer` would only be needed if the output is (or recursively contains) the `Mystruct` type.

Alternatively, you could use `cmp.FilterPath`, which since `0.3.0` is strictly more powerful than `cmp.FilterValues`. Every `cmp.PathStep` in the `cmp.Path` has a [`Values`](https://godoc.org/github.com/google/go-cmp/cmp#PathStep.Values) method, which can be used to interrogate information about the parent values.

Thus, you could do something like this:
```go
cmp.FilterPath(func(p Path) bool {
    // Filter specifically for accesses to the Mystruct.Data field.
    if p.Index(-2).Type() != reflect.TypeOf(Mystruct{}) {
    	return false
    }
    if sf, ok := p.Index(-1).(cmp.StructField); !ok || sf.Name != "Data" {
    	return false
    }

    // Filter specifically for some specific data type.
    x, y :=  p.Index(-2).Values()
    return x.(Mystruct).DataType == sometype && y.(Mystruct).DataType == sometype
}, cmp.Transformer("sometypeTransformer", func(b []byte) T {
   return unmarshalSometype(b)
}))
```

**Comment by dsnet** [comment]
Here's a more advanced example with multiple transformed types:
```go

cmp.FilterPath(func(p cmp.Path) bool {
    // Filter specifically for accesses to the Mystruct.Data field.
    if p.Index(-2).Type() != reflect.TypeOf(Mystruct{}) {
    	return false
    }
    if sf, ok := p.Index(-1).(cmp.StructField); !ok || sf.Name != "Data" {
    	return false
    }
}, cmp.Options{
	// The sub-options below can safely assume that the filter above is applied.

	// This filter only applies on "fooType".
	cmp.FilterPath(func(p cmp.Path) bool {
	    x, y :=  p.Index(-2).Values()
	    return x.(Mystruct).DataType == fooType && y.(Mystruct).DataType == fooType
	}, cmp.Transformer("unmarshalFoo", func(b []byte) Foo {
		return unmarshalFoo(b)
	}),

	// This filter only applies on "barType".
	cmp.FilterPath(func(p cmp.Path) bool {
	    x, y :=  p.Index(-2).Values()
	    return x.(Mystruct).DataType == barType && y.(Mystruct).DataType == barType
	}, cmp.Transformer("unmarshalBar", func(b []byte) Bar {
		return unmarshalBar(b)
	}),

	// In case you're wondering what happens when x.DataType != y.DataType,
	// then none of the options apply and cmp will compare Mystruct as a normal
	// struct, which would report a difference (which is probably what you want).
})
```

**Comment by F21** [comment]
Thanks @dsnet ! That was very useful. You should consider adding the example code as an example in the godoc.

**Comment by dsnet** [comment]
Glad I could help!

> You should consider adding the example code as an example in the godoc.

Yea, the examples could use some love. It's on my list of things to do someday.
