### ISSUE TITLE
How to ignore date fields in JSON

### ISSUE THREAD

**Issue by tiagomelo** [google/go-cmp#156]
Hi, 

I'm working in a project that compares two JSONs in unit tests this way:

if diff := cmp.Diff(string(expected), string(got)); diff != "" {
     fmt.Println(string(got))
     t.Errorf("%s: (-want, +got)\n%s", fixturePath, diff)
}

These JSONs have datetime fields and I want to ignore those fields. I really don't want to compare them. How can I accomplish this?

the Diff() method accepts some options, right?

Best regards,

Tiago

**Comment by dsnet** [comment]
Here's one possible way of doing it: https://play.golang.org/p/PKGzR3fXs-P

General approach:
* Use a transformer to convert a JSON string into a structured representation that `cmp` can understand.
* Use an ignore option (filtered to only apply on strings that look like some date format) to ignore all values of such form. If you only want to ignore a specific time field in the JSON, you'll need to craft a more complex filter function to select that value.

Hope this helps.

**Comment by tiagomelo** [comment]
Hi! Thanks very much for your help.

Your snippet surely works, but when I applied it to the project, I've got:

	"github.com/google/go-cmp/cmp".Option does not implement "github.com/nytm/personalization-reading-list/vendor/github.com/google/go-cmp/cmp".Option (missing "github.com/nytm/personalization-reading-list/vendor/github.com/google/go-cmp/cmp".filter method)

I'm wondering if it's a version issue?

**Comment by dsnet** [comment]
This seems to be an issue that is beyond this project. If I could guess, you might  be running in module mode, where the vendor is not being respected.

I recommend fully embracing modules and avoid use of vendor. In my experience, the vendor approach has been nothing but trouble.

**Comment by tiagomelo** [comment]
Thanks again! Will work into that.

best regards!
