### ISSUE TITLE
comparer not called with different concrete types of interface

### ISSUE THREAD

**Issue by cjnosal** [google/go-cmp#161]
https://godoc.org/github.com/google/go-cmp/cmp#Comparer states "If T is an interface, it is possible that f is called with two values of different concrete types that both implement T."

I'm trying to compare different concrete types of an interface, but my Comparer is never called.

Running:
```
package main

import (
	"github.com/google/go-cmp/cmp"
)

func main() {
	var i1 I
	var i2 I
	
	i1 = &A{}
	i2 = &B{}
	
	cmp.Equal(i1, i2, cmp.Comparer(ic))
	
	panic("not compared")
}

type I interface {
  Foo()
}

type A struct {}
func(a *A) Foo() {}

type B struct {}
func(b *B) Foo() {}

func ic(i1 I, i2 I) bool {
        panic("compared")
}
```
Results in:
```
panic: not compared

goroutine 1 [running]:
main.main()
        /tmp/main.go:16 +0x111
exit status 2
```

```
$ go version
go version go1.13 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cjnosal/.cache/go-build"
GOENV="/home/cjnosal/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/d/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build444735255=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dsnet** [comment]
The issue at hand is that is that when you call a function in Go where the argument is an interface, the exact type of the interface is lost. This is the reason why the following does not do what most users expect:
```go
var r io.Reader
t := reflect.TypeOf(r) // users expect this to be io.Reader, but its actually nil
```
The workaround is usually to take a reference to the interface and them dereference it:
```go
var r io.Reader
t := reflect.TypeOf(&r).Elem() // now t is actually an io.Reader
```

Similarly, directly calling `cmp.Equal` with `i1` and `i2` is actually giving it values of the concrete `*A` and `*B` type, rather than the `I` interface.

A workaround is to instead pass `&i1` and `&i2` instead. [Doing so fixes the issue](https://play.golang.org/p/m8I_tBDABdW).

It's not clear to me that this is a problem with the `cmp` package, but more so a gotcha with the Go language.

**Comment by cjnosal** [comment]
@dsnet Thank you. Regarding the docs, when can the Comparer be "called with two values of different concrete types"? Your explanation makes it sound like it can't?

**Comment by dsnet** [comment]
In the [adjusted playground example](https://play.golang.org/p/m8I_tBDABdW) sent earlier, `Comparer` is being called with two different concrete types.

**Comment by dsnet** [comment]
This [playground example](https://play.golang.org/p/BGqX_2xib1H) makes it even more clear. It panics with:
`panic: comparing *main.A and *main.B`

**Comment by cjnosal** [comment]
I see. I missed that the Comparer signature was still for type `I` when Equal is called with `*I`, and Equal is dereferencing when considering if a Comparer is valid for the type.

**Comment by cjnosal** [comment]
The docs mention 'The comparer f must be a function "func(T, T) bool" and is implicitly filtered to input values assignable to T'. Does this mean that `*A` and `*B` are not considered assignable to `I` when implicitly filtered?

**Comment by xtreme-conor-nosal** [comment]
@dsnet

**Comment by dsnet** [comment]
> Does this mean that *A and *B are not considered assignable to I when implicitly filtered?

I'm not sure what you mean. Both `*A` and `*B` implement `I`, and so are [by definition assignable](https://golang.org/ref/spec#Assignability) to an argument of type `I`. For this reason, the `Comparer` provided is actually being called.

**Comment by xtreme-conor-nosal** [comment]
I'm trying to reconcile this conversation with the documentation:

If I call `cmp.Equal(i1, i2, cmp.Comparer(ic))` in my original example
the exact type of the interface is lost in the call
so the effective call is `cmp.Equal(*A, *B, cmp.Comparer(func(I, I) bool))`
Comparers are filtered by "input values assignable to T"
*A and *B are assignable to I
But the func(I, I) Comparer is still filtered out?

**Comment by dsnet** [comment]
As stated in https://github.com/google/go-cmp/issues/161#issuecomment-537786843, a gotcha of the language is that top-level calls to a function lose information about the interface type.

Thus, at the type-level, the types of  `*A` and `*B` are not `I`, but `interface{}`. Since `interface{}` is not assignable to `I`, the comparer is not called.

**Comment by xtreme-conor-nosal** [comment]
I'm not seeing the loss of type information. In this example I can verify assignability of interface{} to I and invoke the function: https://play.golang.org/p/P6nhXcSJteC

**Comment by nhooyr** [comment]
> Thus, at the type-level, the types of *A and *B are not I, but interface{}. Since interface{} is not assignable to I, the comparer is not called.

Why not use the concrete type to check assignability instead? This is pretty confusing given the docs state:

>  If T is an interface, it is possible that f is called with two values of different concrete types that both implement T.

**Comment by dsnet** [comment]
Several reasons:
1) The wording used matches the those of the Go language specification, and the behavior matches that of the Go reflect package (which is functionally a dynamic implementation of the Go language).
2) It's non-trivial (but do-able) to implement this as it requires descending into the concrete types of an interface first, checking whether any options apply on those concrete types before coming back and performing the general type equality check. 
3) It's too late to change the behavior. If `cmp` were being doing over from afresh, perhaps we should have done it the way that leads to less gotchas. When I experimented with the changed behavior, it broke a lot of targets.

**Comment by gonzojive** [comment]
I frequently find myself tripping over this issue or a similar issue, and it's difficult to figure out how to write the appropriate `cmp.Option`s to fix it, debug why a transformer is not being applied, etc.

I don't follow the subtlety of the language in the documentation, even after reading over this thread. [Here is my test program](https://play.golang.org/p/-m-AKP5GIv7). The body of main is the interesting bit:

```go
transformCount := 0
// "The transformer f must be a function "func(T) R" that converts values of
// type T to those of type R and is implicitly filtered to input values
// assignable to T. The transformer must not mutate T in any way."
f := func(i I) string {
	transformCount++
	fmt.Printf("transformIToFoo(%+v) called, got %q\n", i, i.Foo())
	return i.Foo()
}
transformIToString := cmp.Transformer("T", f)
var a1, a2 interface{} = &AlwaysA{}, &AnotherImpl{"A"}
_, isA1AssignableToI := a1.(I)
_, isA2AssignableToI := a2.(I)
explainAssignability("a1", isA1AssignableToI)
explainAssignability("a2", isA2AssignableToI)
T := reflect.ValueOf(f).Type().In(0)
explainAssignability("a1", reflect.ValueOf(a1).Type().AssignableTo(T))
explainAssignability("a2", reflect.ValueOf(a2).Type().AssignableTo(T))

fmt.Printf("diff1: %s\n", cmp.Diff(a1, a2, transformIToString))
fmt.Printf("transform count: %d\n", transformCount)
```

produces 
```
=============== case 1 =================
a1 IS assignable to I
a2 IS assignable to I
a1 IS assignable to I
a2 IS assignable to I
diff1:   interface{}(
- 	&main.AlwaysA{},
+ 	&main.AnotherImpl{foo: "A"},
  )
```
As far as I can tell, the input values `a1` and `a2` are assignable to I. What am I missing?

**Comment by dsnet** [comment]
In Go, the only possible way you can have two different concrete types is in an interface. In the [documented behavior of `cmp.Equal`](https://pkg.go.dev/github.com/google/go-cmp/cmp#Equal) it says (regarding interfaces):
> Pointers and interfaces are equal if they are both nil or both non-nil, **where they have the same underlying concrete type** and recursively calling Equal on the underlying values reports equal.

The phrase **where they have the same underlying concrete type** is not satisfied, so logic doesn't even get to the point where it checks for assignability to any comparers that were provided.

I don't think we can change the default behavior of this now. However, it's probably worth exploring how to make your specific use case work, but it opens a can of worms regarding gnarly type variance issues.

**Comment by gonzojive** [comment]
What confused me about that description of the algorithm (`cmp.Equal`) is that three bullets appear before the language you are quoting, the first one of which seems to apply to the values `a1` and `a2` (as `x` and `y` in the param list of `cmp.Equal`):

> * Let S be the set of all Ignore, Transformer, and Comparer options that remain after applying all path filters, value filters, and type filters. If at least one Ignore exists in S, then the comparison is ignored. If the number of Transformer and Comparer options in S is greater than one, then Equal panics because it is ambiguous which option to use. If S contains a single Transformer, then use that to transform the current values and recursively call Equal on the output values. If S contains a single Comparer, then use that to compare the current values. Otherwise, evaluation proceeds to the next rule.
> * If the values have an Equal method of the form "(T) Equal(T) bool" or "(T) Equal(I) bool" where T is assignable to I, then use the result of x.Equal(y) even if x or y is nil. Otherwise, no such method exists and evaluation proceeds to the next rule.
> 
> * Lastly, try to compare x and y based on their basic kinds. Simple kinds like booleans, integers, floats, complex numbers, strings, and channels are compared using the equivalent of the == operator in Go. Functions are only equal if they are both nil, otherwise they are unequal.
> 
> Structs are equal if recursively calling Equal on all fields report equal. If a struct contains unexported fields, Equal panics unless an Ignore option (e.g., cmpopts.IgnoreUnexported) ignores that field or the Exporter option explicitly permits comparing the unexported field.
> 
> Slices are equal if they are both nil or both non-nil, where recursively calling Equal on all non-ignored slice or array elements report equal. Empty non-nil slices and nil slices are not equal; to equate empty slices, consider using cmpopts.EquateEmpty.
> 
> Maps are equal if they are both nil or both non-nil, where recursively calling Equal on all non-ignored map entries report equal. Map keys are equal according to the == operator. To use custom comparisons for map keys, consider using cmpopts.SortMaps. Empty non-nil maps and nil maps are not equal; to equate empty maps, consider using cmpopts.EquateEmpty.
> 
> Pointers and interfaces are equal if they are both nil or both non-nil, where they have the same underlying concrete type and recursively calling Equal on the underlying values reports equal.
> 
> Before recursing into a pointer, slice element, or map, the current path is checked to detect whether the address has already been visited. If there is a cycle, then the pointed at values are considered equal only if both addresses were previously visited in the same path step.

The piece about how interfaces are treated by comparing concrete types seems to be part of the third bullet, though it is hard to tell with the formatting in godoc. I would not expect the algorithm to ever reach that point of execution since the first bullet seems to apply.

===

In any case, I take your point about the default behavior. Perhaps you can supply a cmp.Option that configures this?

I think I got it to work for the playground example earlier:

```
	transformCount := 0
	// "The transformer f must be a function "func(T) R" that converts values of
	// type T to those of type R and is implicitly filtered to input values
	// assignable to T. The transformer must not mutate T in any way."
	f := func(i interface{}) string {
		transformCount++
		return i.(I).Foo()
	}
	opt := cmp.FilterValues(func(x, y interface{}) bool {
		_, ok1 := x.(I)
		_, ok2 := y.(I)
		return ok1 && ok2
	}, cmp.Transformer("T", f))
	var a1, a2 interface{} = &AlwaysA{}, &AnotherImpl{"B"}

	fmt.Printf("diff1: %s\n", cmp.Diff(a1, a2, opt))
	fmt.Printf("transform count: %d\n", transformCount)
    // Outputs transform count: 6
```

**Comment by gonzojive** [comment]
My specific use case can be replicated with

```shell
git clone --branch wirepath https://github.com/gonzojive/xtoproto.git
cd xtoproto
# git checkout ec083e522355913a0667a80acf28900b696ace29
bazel test //wirepath:wirepath_test
```
The approach I pasted isn't yet working in the xtoproto test case for some reason.

**Comment by shwoodard** [comment]
Why not check if the return value of `Kind()` is `reflect.Ptr` and take `Elem()` in that case (iiuc)?

**Comment by rogpeppe** [comment]
FWIW this behaviour makes Comparer way less useful. For example, it's common to store values inside `any`, but there's no way to have comparison behaviour that is triggered by the value that's inside that interface value.

Also, this seems very inconsistent:

> The wording used matches the those of the Go language specification, and the behavior matches that of the Go reflect package (which is functionally a dynamic implementation of the Go language).

If this were actually the case, then this example would not work, because `any` is not assignable to `int`.

```
	cmp.Equal(1, 2, cmp.Comparer(func(s1, s2 int) bool {
		panic("compared")
	}))
```

The above seems to work because the _concrete value_ is assignable to `int`, but
if that's the assignability check we're using then it should apply for interface
types too.

I think this behaviour should be changed (maybe guarded by an option initially to keep backwards compatibility, although I suspect that not much would break).
