### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by anicoll** [google/go-cmp#166]
reading docs has method `EquateApproxTime` but latest release is from 8th Aug 2019.

**Comment by hibiken** [comment]
+1
I have the latest version installed, but was not able to use `EquateApproxTime`

**Comment by dsnet** [comment]
I'll be landing a few more substantial changes in the upcoming days. We'll tag the next point release on January 1st so that there's time to soak in the new changes in case there's something that needs to be fixed.

**Comment by dsnet** [comment]
Done.
