### ISSUE TITLE
How to get Diff for structs with error field?

### ISSUE THREAD

**Issue by IRuslan** [google/go-cmp#172]
For this pretty simple example:

```
type Cmp struct {
  Err error
}

a := Cmp{
  Err: errors.New("got an error"),
}

b := Cmp{
  Err: errors.New("got a wrong error"),
}

diff := cmp.Diff(a, b)
```

I've got a panic:
```
panic: cannot handle unexported field: {Cmp}.Err.(*errors.errorString).s
consider using a custom Comparer; if you control the implementation of type, you can also consider AllowUnexported or cmpopts.IgnoreUnexported
```
Seems there is no way to use AllowUnexported to make cmp.Diff() possible.
Is there any solution?

**Comment by neild** [comment]
You can provide a custom Comparer option that defines how you want to compare `errors` values.

For example, one possibility (using Go 1.13's `errors.Is`) might be:

```go
if diff := cmp.Diff(a, b, cmp.Comparer(func(x, y error) bool {
  // Two errors are equal if either Is the other.
  //
  // We need to perform the test in both directions because cmp requires
  // comparer functions to be symmetric, but errors.Is is not.
  return errors.Is(x, y) || errors.Is(y, x)
})); diff != "" {
  // something changed
}
```

You might also use `x == y` for a strict equality check, `(x == nil) == (y == nil)` to compare only nil-ness, or some other test.

**Comment by IRuslan** [comment]
To be sure I understand you correctly. In my example, the field is an error interface. 
Does it mean inside the Comparer function I need to access those fields manually?
E.g. `x.Err` and `y.Err`? Does it also mean I need to handle a comparison of all remaining fields inside the Comparer?

**Comment by neild** [comment]
Here's a working example:
https://play.golang.org/p/qTJqbwV9wf0

The comparison function is called with when comparing values of the appropriate type (`error` in this case).

**Comment by IRuslan** [comment]
@neild thanks a lot.
