### ISSUE TITLE
cmp two same slice, but sub item is unordered

### ISSUE THREAD

**Issue by allenhaozi** [google/go-cmp#175]
`
type Item struct {
	Media string
	Size  int64
}

func main() {

	standard := []Item{
		Item{
			Media: "SSD",
			Size:  100,
		},

		Item{
			Media: "HDD",
			Size:  200,
		},
	}

	test1 := []Item{
		Item{
			Media: "HDD",
			Size:  200,
		},
		Item{
			Media: "SSD",
			Size:  100,
		},
	}

	fmt.Println(cmp.Equal(standard, test1))

}
want: true, got: false
`

**Comment by allenhaozi** [comment]
`func Equal(x, y interface{}, opts ...Option) bool`

later, I use opts solved it, can it handle the disorder case without additional  opts

**Comment by dsnet** [comment]
> later, I use opts solved it, can it handle the disorder case without additional opts

No. `cmp.Equal` has a well-defined set of rules that it follows. Specifically, it says that it cares about ordering of slices. You may want to take a look at [`cmpopts.SortSlices`](https://godoc.org/github.com/google/go-cmp/cmp/cmpopts#SortSlices).
