### ISSUE TITLE
Generated doc 

### ISSUE THREAD

**Issue by astaluego** [google/go-cmp#179]
Hello, 

on https://godoc.org/github.com/google/go-cmp/cmp, the function Reporter on the Index is not well readable because of the comments inside the signature of the function 🙂 

<img width="1061" alt="Capture d’écran 2019-12-16 à 17 09 33" src="https://user-images.githubusercontent.com/6352288/70923165-b888ae00-2027-11ea-80b9-caa265f12a6e.png">

**Comment by dsnet** [comment]
This is a known issue with godoc and the fix for it has yet to land. Nothing to do on `cmp`'s end.

**Comment by dsnet** [comment]
The new go.dev site renders this corerctly: https://pkg.go.dev/github.com/google/go-cmp/cmp?tab=doc

**Comment by astaluego** [comment]
Yes !
