### ISSUE TITLE
nil slice/map should compare equal to empty slice/map

### ISSUE THREAD

**Issue by rogpeppe** [google/go-cmp#18]
The documentation states:

	Slices and arrays are equal if they have the same length and the elements
	at each index are equal. Maps are equal if their keys are exactly equal
	(according to the == operator) and the corresponding elements for each
	key are equal.

I read this as implying that this program would print `true true`, but
instead it prints `false false`.

	package main
	
	import (
		"github.com/google/go-cmp/cmp"
		"log"
	)
	
	func main() {
		log.Println(
			cmp.Equal(map[int]string{}, map[int]string(nil)),
			cmp.Equal([]int{}, []int(nil)),
		)
	}

**Comment by rogpeppe** [comment]
For the record, here's a (somewhat awkward) workaround for slices

		cmp.FilterValues(func(x, y interface{}) bool {
			if x == nil || y == nil {
				return false
			}
			xv, yv := reflect.ValueOf(x), reflect.ValueOf(y)
			xt, t1 := xv.Type(), yv.Type()
			return xt.Kind() == reflect.Slice &&
				t1.Kind() == reflect.Slice &&
				xv.Len() == 0 &&
				yv.Len() == 0 &&
				(xv.IsNil() != yv.IsNil())
		}, cmp.Transformer("nilSlice", func(in interface{}) interface{} {
			return reflect.Zero(reflect.TypeOf(in)).Interface()
		}))

**Comment by rogpeppe** [comment]
... and now I see cmpopts.EquateEmpty!

I suggest a documentation update, because the documentation does not make
it clear that EquateEmpty or the like would be required (a nil slice has the same
number of elements as an empty slice).

**Comment by dsnet** [comment]
Yea, the documentation for this is misleading.
