### ISSUE TITLE
Expose Tag of reflect.StructField?

### ISSUE THREAD

**Issue by corneliusweig** [google/go-cmp#183]
I'm trying to write a reporter that produces yaml output. For that I need to get access to the `Tag` property on `cmp.StructField`.

Would you be willing to expose this via
```go
func (sf *StructField) Tag() reflect.StructTag {
	return sf.field.Tag
}
```

Or does this break some abstraction level that I did not think of?

**Comment by dsnet** [comment]
Currently, you can get it as follows:
```go
if sf, ok := p.Index(i).(cmp.StructField); ok {
    t := p.Index(i-1).Type()
    tag := t.Field(sf.Index).Tag
}
```
This works because the type of the previous path step must be a struct type.

**Comment by corneliusweig** [comment]
Oh sure, that's it! It also makes much more sense like this.

And many thanks for your speedy response!
