### ISSUE TITLE
Nested Equal method of a type

### ISSUE THREAD

**Issue by guiguan** [google/go-cmp#184]
If a type defines an `Equal` method that in turn uses `cmp.Equal`, then it will enter an infinite loop. It will be quite helpful if the type's Equal method could be implemented using `cmp.Equal` with complex options. Any idea of how to handle this situation?

**Comment by dsnet** [comment]
You can try the following:
```go
func (x T) Equal(y T) bool {
    type T2 T
    return cmp.Equal(T2(x), T2(y))
}
```

The [type declaration](https://golang.org/ref/spec#TypeDef) of `T2` has the exact same underlying memory layout as `T`, but lacks any of the methods. Per the Go specification:
> It does not inherit any methods bound to the given type

This ensures that it does not inherit the `Equal` method.

You can now cast to `T2` and call `cmp.Equal` on the values.

The same thing works for pointers as well:
```go
func (x *T) Equal(y *T) bool {
    type T2 T
    return cmp.Equal((*T2)(x), (*T2)(y))
}
```

**Comment by guiguan** [comment]
@dsnet that's nice. Thanks for the tip.
