### ISSUE TITLE
How to apply cmpopts.EquateEmpty() recursively?

### ISSUE THREAD

**Issue by qdm12** [google/go-cmp#186]
Hi there,

First of all, thanks for the great library.

I noticed using the option cmpopts.EquateEmpty() does not apply to fields of structs (or recursively). Is there an option to do so? I keep on reading the docs but cannot figure how.

```go
x := struct{ a []int }{} // nil slice in struct
y := struct{ a []int }{[]int{}} // empty slice in struct
fmt.Println(cmp.Equal(x, y, cmpopts.EquateEmpty())) // false
```

Thanks!

**Comment by dsnet** [comment]
Hi, sorry to hear about your troubles. Unfortunately, I'm not able to replicate the issue: https://play.golang.org/p/Zw00duqujKn. It seems to print `true` for me.

**Comment by qdm12** [comment]
That was a quick answer! Thanks so much.

Indeed, sorry for messing this up the library works as intended.

I think my problem is that cmp is picking up on Equal defined methods on types of subfields. Is there a way to prevent cmp from using these `.Equal(..)` methods maybe? Thanks!

I'll close the issue as it's irrelevant now.
