### ISSUE TITLE
Compare struct with inheritance

### ISSUE THREAD

**Issue by maeglindeveloper** [google/go-cmp#187]
Hi everyone, 

I'm actually trying to compare objects of a structure using some inheritance. Here are the definitions of my structure :
```
type A struct {
	ID string
}
type B struct {
	A
	ChildID string
}
```
To get the differences between 2 objects, I wanted to use a custom reporter to only get the "path" of each modified attributes. Here is my custom reporter :
```
func (r *DiffReporter) Report(rs cmp.Result) {
	if !rs.Equal() {
		r.Diffs = append(r.Diffs, r.path.String())
	}
}
```
The `r.path.String()` instruction returns path like this one : `A.ID`. Is there a way to not have the name of the "parent" structure (in this case, the structure `A`) into the path ? 

Thanks in advance 👍

**Comment by dsnet** [comment]
As a goal, `cmp` strives hard to avoid reporting anything that is ambiguous. Dropping the `A` segment produces a degree of ambiguity if there's ever a conflicting `ID` field:
```go
type A struct {
	ID string
}
type B struct {
	ID string
}
type C struct {
	A
	B
	ChildID string
}
```
In this case, there's a namespace conflict over `ID` as both `A` and `B` forward it to `C`. Always printing the parent type when embedding is both simpler and more clear, but understandably can be more verbose.

**Comment by dsnet** [comment]
I should note that the logic of `Path.String` is not particularly complicated:
https://github.com/google/go-cmp/blob/5a6f75716e1203a923a78c9efb94089d857df0f6/cmp/path.go#L98-L106

It should be palatable write a local version does what's requested.

**Comment by dsnet** [comment]
Closing since there's a user workaround.
