### ISSUE TITLE
Allow explicitly opting into line diffs for string comparison

### ISSUE THREAD

**Issue by rliebz** [google/go-cmp#192]
Since https://github.com/google/go-cmp/pull/131, comparisons of large blocks of string text can often display line-by-line diffs, which is a great feature. Currently, it relies on best guess heuristics to determine whether a line-by-line diff should be used or not.

In particular, if any line in the text blob is longer than 256 characters, line-by-line diffs are disabled:
https://github.com/google/go-cmp/blob/f6dc95b586bc4e5c03cc308129693d9df2819e1c/cmp/report_slices.go#L100

My particular use case is for comparing large blobs of formatted JSON. Due to the structure of JSON strings, we often get back blobs that are mostly sane and may have one or two long strings that exceed 256 characters. I would like to be able to opt-in to using the line-by-line diff, even if my text blobs fail the heuristic.

**Comment by dsnet** [comment]
We've been trying to make the default reporter as good as it can be (with a set of decent heuristics). We know that it won't be perfect, but the hope is that it's good enough. On a philosophical level, we tend to shy away from providing knobs to control how things are formatted and reported.

That said, have you considered just using a transformer to obtain more structured output? If you're dealing with JSON, you could do something like:
```go
cmpopts.AcyclicTransformer("ParseJSON", func(in []byte) (out interface{}) {
    if err := json.Unmarshal(in, &out); err != nil {
        return in
    }
    return out
})
```
This will give you superior diffing of JSON objects than any features that could reasonably be added to the reporter.

**Comment by dsnet** [comment]
If returning the input in the case of an error feels weird, you can also do:
```go
cmp.FilterValues(func(x, y []byte) bool {
    return json.Valid(x) && json.Valid(y)
}, cmpopts.AcyclicTransformer("ParseJSON", func(in []byte) (out interface{}) {
    json.Unmarshal(in, &out) // guaranteed to succeed
    return out
}))
```

**Comment by rliebz** [comment]
I completely understand the desire to keep the API surface small.

For my use case, I'm avoiding rely on Go data structures for JSON comparison because of small differences like `{"foo": ""}` versus `{"foo":null}` versus `{}` when data are unavailable, which are difficult to represent using structs.

That said, I think I can use `cmpopts.AcyclicTransformer` to get a line-by-line diff by just splitting strings on the newline character:
```go
cmp.Diff(
  blob1, blob2, 
  cmpopts.AcyclicTransformer("multiline", func(s string) []string {
    return strings.Split(s, "\n")
  }),
)
```

Some basic testing of that is giving me the exact kind of output I was looking for, so I'm happy with that as a solution.

Thanks for the quick response!
