### ISSUE TITLE
Different objects are formatted identically

### ISSUE THREAD

**Issue by ArseniiPetrovich** [google/go-cmp#194]
Hi, guys. I'm trying to write a set of tests that will compare existing security group with a predefined ones. For that I'm using this library to compare two groups - the one that is received via AWS DescribeSecurityGroups request and the one I define.

The predefined struct is:
```
var rules = []ec2.IpPermission {
                ec2.IpPermission {
                  FromPort: &fromPorts[0],
                  IpProtocol: &ipProtocols[0],
                  IpRanges: []*ec2.IpRange {
                    &ec2.IpRange {
                      CidrIp: &cidrIPs[0],
                    },
                  },
                  ToPort: &toPorts[0],
                },
}
```

When I compared it for the first time I got "false" result and decided to add some logging to figure out the root of the issue.  The cmp.Diff gave me the following output:

```
    TestBundle/Security_groups_tests: bundle_test.go:338: DEBUG. That is no match. The difference is:                                 
    TestBundle/Security_groups_tests: bundle_test.go:339:   interface{}(                                                              
        -       s"{\n  FromPort: 30333,\n  IpProtocol: \"tcp\",\n  IpRanges: [{\n      CidrIp: \"0.0.0.0/0\"\n    }],\n  ToPort: 30333
\n}",                                                                                                                                 
        +       s"{\n  FromPort: 30333,\n  IpProtocol: \"tcp\",\n  IpRanges: [{\n      CidrIp: \"0.0.0.0/0\"\n    }],\n  ToPort: 30333
\n}",                                                                                                                                 
          )
```

As you can see there is a perfect match of two objects, however they are not equal according to cmp.Equal method.

**Comment by dsnet** [comment]
Without runnable code, there isn't much we can do to debug this. Typically when something like this happens, it's because cmp is comparing upon some value that is incomparable (e.g., a cache, a mutex, a floating-point NaN, etc).

**Comment by ArseniiPetrovich** [comment]
Hi, @dsnet! Thank you for such a quick answer. Our project is going to be published under Apache 2.0 license, so I think there's no problem for me to share this project with you now. I've added you to our private repo as an outside collaborator. Please, check your email for details. 
Our Golang scripts reside in `tests/aws` folder. The function I have issue with is called `SGCheck`. Thanks!

**Comment by dsnet** [comment]
Following up here: I don't think I ever got any such link in my email.

**Comment by ArseniiPetrovich** [comment]
@dsnet 
Please, use this link => https://github.com/Altoros/polkadot-validator-failover/invitations
It should point you directly to our repo. Thank you!

**Comment by ArseniiPetrovich** [comment]
Oops. Accidentally closed 🥇

**Comment by ArseniiPetrovich** [comment]
@dsnet Any progress on this issue? We could probably schedule a call to work on this issue?

**Comment by ArseniiPetrovich** [comment]
Okay, I was finally able to identify the issue. I was comparing the array of object with array of pointers to objects. The problems is that `cmp.Diff` does not show this difference, which complicated the identification of problems. I would recommend to add more verbose info to Diff function.
