### ISSUE TITLE
Allow usage of AllowUnexported() and IgnoreFields()

### ISSUE THREAD

**Issue by gauntface** [google/go-cmp#196]
I have hit a few scenarios where I want to compare some unexported fields but not all and I can't use AllowUnexported and IgnoreFields together.

```go
opts := []cmp.Option{
	cmp.AllowUnexported(Client{}),
	cmpopts.IgnoreFields(Client{}, "httpNewRequest"),
}
if diff := cmp.Diff(got, tt.want, opts...); diff != "" {
	t.Fatalf("Unexpected result; diff %v", diff)
}
```

Results in a panic: `name must be exported`

**Comment by dsnet** [comment]
It's been on my radar to have `cmpopts.IgnoreFields` work with unexported fields. If you want to try and enable this, feel free to send a PR.
