### ISSUE TITLE
Displaying uints in cmp.Diff output in decimal notation rather than hexadecimal

### ISSUE THREAD

**Issue by EivindSt** [google/go-cmp#219]
When comparing uint slices with `cmp.Diff` the output displays differences as hexadecimal strings. While this is easily readable for e.g. bytes, it can be confusing when debugging larger numbers.
It would be nice to have options to control the format used to output numbers.

E.g. the following test:

```go
func TestCmpDiffUint(t *testing.T) {
	if diff := cmp.Diff([]uint{0, 1, 2, 128}, []uint{1, 1, 2, 127}); diff != "" {
		t.Fatalf(diff)
	}
}
```
produces the output:
```
--- FAIL: TestCmpDiffUint (0.00s)
    cmp_test.go:11:   []uint{
        - 	0x00, 0x01, 0x02, 0x80,
        + 	0x01, 0x01, 0x02, 0x7f,
          }
```

In comparison, when comparing `[]int` slices with the following test:

```go
func TestCmpDiffInt(t *testing.T) {
	if diff := cmp.Diff([]int{0, 1, 2, 128}, []int{1, 1, 2, 127}); diff != "" {
		t.Fatalf(diff)
	}
}
```
the following output is produced:
```
--- FAIL: TestCmpDiffInt (0.00s)
    cmp_test.go:17:   []int{
        - 	0, 1, 2, 128,
        + 	1, 1, 2, 127,
          }
```
which is arguably more readable.

**Comment by dsnet** [comment]
Thanks for the report. This is already fixed by #199
