### ISSUE TITLE
Transformer not getting applied

### ISSUE THREAD

**Issue by adarshk-rapido** [google/go-cmp#222]
I have a use case of transforming float to int while using `go-cmp` and I'm trying out with following code based on examples from docs, but it's not applying the transformer when I check the Diff output.

## Sample Code

```
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
)

func main() {

	opt := cmp.Transformer("T3", func(in float64) int {
		return int(in)
	})

	c1 := map[string]interface{}{"a": 0}
	c2 := map[string]interface{}{"a": float64(0)}
	
	fmt.Println(cmp.Diff(c2, c1, opt))
	fmt.Println(cmp.Equal(c2, c1, opt))

}

```
## Output
```  
map[string]interface{}{
- 	"a": int(0),
+ 	"a": float64(0),
  }

false
```

What am I missing here ?

https://play.golang.org/p/4oCeVLsMo2U

**Comment by dsnet** [comment]
Per the documented rules of evaluation:

> Pointers and interfaces are equal if they are both nil or both non-nil, where they have the same underlying concrete type and recursively calling Equal on the underlying values reports equal.

The underlying concrete types in the interface are different (`int` vs `float64`), so the comparison is reporting a difference before your transformer (which only operates on `float64`) gets a chance to run.

If you modify the transformer to operate on a `interface{}`, then it works as you would expect: https://play.golang.org/p/siWPyVr77mD

In that example, the transformer operates on `interface{}`, but specifically filtered for values that are of any type convertible to a `float64` and transforms it to be a `float64`.

**Comment by adarshk-rapido** [comment]
thank you very much this was so helpful. Sorry I missed that part of the documentation.

**Comment by dsnet** [comment]
Glad it helped.

>Sorry I missed that part of the documentation.

No worries, it's easy to not quite get the order of operations that cmp works in, but once you do, it becomes much easier to understand what's going on.
