### ISSUE TITLE
Allow applying options to all types

### ISSUE THREAD

**Issue by howardjohn** [google/go-cmp#223]
We have a case where we want to compare two objects. These happen to be extremely nested objects from https://github.com/envoyproxy/go-control-plane. They recently added new unexported fields, as will *all* users of golang/protobuf when they update to 1.4+. This breaks go-cmp out of the box, with errors like
```
panic: cannot handle unexported field at {[]*envoy_config_cluster_v3.Cluster}[1].Http2ProtocolOptions.state:
	"github.com/envoyproxy/go-control-plane/envoy/config/core/v3".Http2ProtocolOptions
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported [recovered]
```

It seems the only way to get around this is to set options for each type to ignore. However, this is not feasible as there are literally thousands of types we need to ignore for.

**Comment by dsnet** [comment]
I think [`google.golang.org/protobuf/testing/protocmp.Transform`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp?tab=doc#Transform) might be what you want?

**Comment by howardjohn** [comment]
@dsnet that is perfect! Especially

> The google.protobuf.Any message is automatically unmarshaled such that the "value" field is a Message representing the underlying message value assuming it could be resolved and properly unmarshaled.

Feel free to close this, this should be pretty searchable for anyone in the future who runs into this

**Comment by dsnet** [comment]
Happy to hear that it helps.
