### ISSUE TITLE
Is there any way to compare two JSON []byte inputs with this library?

### ISSUE THREAD

**Issue by arvenil** [google/go-cmp#224]
Is there any way to compare two JSON []byte inputs with this library?
Something similar to testify/assert.JSONEq() https://github.com/stretchr/testify/blob/master/assert/assertions.go#L1526 ?

**Comment by dsnet** [comment]
You could implement our own transformer:
```go
transformJSON := cmp.FilterValues(func(x, y []byte) bool {
    return json.Valid(x) && json.Valid(y)
}, func("ParseJSON", func(in []byte) (out interface{}) {
    json.Unmarshal(in, &out)
    return out
})) 
```

**Comment by arvenil** [comment]
Why not add this as default to `Diff()`? Seems rather common to compare JSONs. I will try it later but looks enough to keep me going. Thanks!!!

**Comment by dsnet** [comment]
> Why not add this as default to Diff()? Seems rather common to compare JSONs

An explicit goal of `cmp` is to treat as few types as possible as special. If JSON is special-cased, why not XML or protobufs, or etc? We need to set a limit somewhere. Furthermore, the more types `cmp` understands, the larger the dependency tree, and we're trying to keep it to a minimum.
