### ISSUE TITLE
question: How To Diff for a  complex data structure

### ISSUE THREAD

**Issue by kaktus42** [google/go-cmp#227]
Hi, I was wondering how I can use this great package to get a better diff output for my complex struct.
I implemented an Equal function on it, but the diff then outputs the whole structure as "added" and "removed".
I created an example here: https://play.golang.org/p/a39oaPKjaGO

Right now the output is
```
  (*main.Foo)(
- 	&{A: 4, B: "abc", C: []*main.Bar{&{x: 1}, &{x: 2}, &{x: 4}}},
+ 	&{A: 4, B: "abc", C: []*main.Bar{&{x: 1}, &{x: 2}, &{x: 3}}},
  )
```

What I want is something like this:
```
  (*main.Foo)(
	&{A: 4, B: "abc", C: []*main.Bar{
 		&{x: 1},
 		&{x: 2},
- 		&{x: 4},
+ 		&{x: 3},
	}},
  )
```

How could I achieve this?

**Comment by dsnet** [comment]
If you want to avoid having the `Equal` method be called, you could use a transformer that strips the `Equal` method:

```go
cmp.Transformer("StripFooMethods", func(f Foo) interface{} {
    type Foo Foo
    return Foo(f)
})
```

This transformer relies on declaring a new type. Per https://golang.org/ref/spec#Type_definitions, the newly declared type has the same underlying memory layout as `Foo` but does not inherit any mounds bound to the underlying type.

For example, he's the technique used to [avoid the `Equal` method of a `time.Time`](https://play.golang.org/p/oNdFGLeeRsv).

**Comment by kaktus42** [comment]
Right. But let's assume that the equality logic is complex and defined in the Equal method, so we want to use it.
How would I proceed then?

**Comment by dsnet** [comment]
There is no workaround for this. It's a can of worms if the reporter were to try and diff the data structures of two objects where equality was not determined by `cmp` as it wouldn't know what semantics to use (e.g., does it equate empty slices? does it compare pointers or does it descend into pointers? etc.).

**Comment by dsnet** [comment]
Closing as inactionable. I don't think there's a way to unify the difference in information as provided by semantic comparison (due to the presence of a `Equal` method) and what the reporter ends up showing. The reporter could try descending into to struct, but what it shows as the diff will be subtly lying about what the semantic comparison determined to be the difference.
