### ISSUE TITLE
go get command errors out on not being in GOROOT

### ISSUE THREAD

**Issue by MelleKoning** [google/go-cmp#265]
for a non GOROOT package, after running:

```
go get -u github.com/google/go-cmp/cmp
go mod vendor
```

And importing `go-cmp` in a test package, go.mod is complaining about the import of the package with:

```
>go test ./...
run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
> go mod vendor
project.com/pkg/packageundertest tested by
        project.com/pkg/packageundertest.test imports
        go-cmp: package go-cmp is not in GOROOT (/usr/local/go/src/go-cmp)
```

Changing go.mod or running `go mod tidy` or `go clean --cache` does not have an effect. How to circumvent this issue?

**Comment by dsnet** [comment]
Hi, this doesn't seem to have anything to do with this module, but something funky is going on with your development environment. I don't know enough about your setup to assist you. I recommend asking on the Gophers Slack workspace: https://gophers.slack.com/messages/general/ for help.

**Comment by MelleKoning** [comment]
Ok, if you are sure the module works fine for projects not in goroot I will recheck and close this issue for now. Thanks for quick response
