### ISSUE TITLE
How to compare int to int64?

### ISSUE THREAD

**Issue by pofl** [google/go-cmp#286]
MWE:
```go
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
)

func main() {
	fmt.Print(cmp.Diff(
		map[string]interface{}{"a": 1, "b": 2, "c": int64(3)},
		map[string]interface{}{"a": int64(1), "b": 2, "c": int64(3)},
		cmp.Transformer("intToInt64", func(i int) int64 { return int64(i) }),
	))
}
```
output:
```
  map[string]interface{}{
- 	"a": int(1),
+ 	"a": int64(1),
  	"b": int(Inverse(intToInt64, int64(2))),
  	"c": int64(3),
  }
```

My idea was to compare int and int64 by casting int to int64.
I expected the comparison to recognize both maps as equal.
How can I achieve the desired behavior? And maybe this has the potential to be added as a prebuilt more general transformer-kind-of-thing for when anybody else wants to compare integers across types.

**Comment by dsnet** [comment]
Hi @pofl,

Option one: Just make sure your golden data uses `int64` instead of `int`. I assume you already know this and there might be a reason that makes this challenging.

Option two: Use a filtered transformer that operates directly on `interface{}`. [Example:](https://go.dev/play/p/cguSd--b4zT):
```go
cmp.FilterValues(func(x, y interface{}) bool {
	isIntX := func(v interface{}) bool {
		switch v.(type) {
		case int, int64:
			return true
		default:
			return false
		}
	}
	return isIntX(x) && isIntX(y)
}, cmp.Transformer("ToInt64", func(v interface{}) int64 {
	if i64, ok := v.(int64); ok {
		return i64
	}
	return int64(v.(int))
})),
```
The filter accepts any `interface{}` that carries either an `int` or `int64` but nothing else. The transformer converts either to just `int64`.

**Comment by dsnet** [comment]
The above filter is more complicated than preferred and could benefit from #277, where it could be simplified as:
```go
cmp.FilterValue(func(v interface{}) bool {
	switch v.(type) {
	case int, int64:
		return true
	}
	return false
}, cmp.Transformer(...))
```

**Comment by pofl** [comment]
Alright thank you very much! My question has been answered. Feel free to hijack this issue to discuss an addition to cmpopts or close it 🙂

**Comment by dsnet** [comment]
Closing as resolved. I'm glad the explanation helped.
