### ISSUE TITLE
Does go-cmp support white/black list?

### ISSUE THREAD

**Issue by SupNewBeen** [google/go-cmp#287]
Say I'm comparing two struct and want to ignore some fields (by using black list) or only want to compare certain fields (by using white list). Does go-cmp support them now?

**Comment by dsnet** [comment]
Ignoring some fields (a black list) is possible with https://pkg.go.dev/github.com/google/go-cmp/cmp/cmpopts#IgnoreFields

Ignoring all fields except some fields (a white list) is not currently provided. That would be #66.

**Comment by dsnet** [comment]
Closing as resolved for the first issue, and a duplicate for the second issue.
