### ISSUE TITLE
FilterValues not working as expected

### ISSUE THREAD

**Issue by ryannealmes** [google/go-cmp#288]
My issue is I can't understand why the option passed to `FilterValues` is not being evaluated. See code below.

```golang
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
)

type MyStruct struct {
	MyField string
}

func main() {

	filter := cmp.FilterValues(
		func(x, y MyStruct) bool {
			return true // I simplified this to return true to demonstrate my issue
		},
		cmpopts.IgnoreFields(MyStruct{},
			"MyField",
		),
	)

	obj1 := MyStruct{MyField: "a"}
	obj2 := MyStruct{MyField: "b"}

	// I would have thought this would have no diffs
	fmt.Println(cmp.Diff(obj1, obj2, filter))

	/// I get this
	// main.MyStruct{
	// 	- 	MyField: "a",
	// 	+ 	MyField: "b",
	// 	  }

	// This has no diffs as expected
	fmt.Println(cmp.Diff(obj1, obj2, cmpopts.IgnoreFields(MyStruct{},
		"MyField",
	)))
}
 ```
I feel like IgnoreFields should be evaluated when using the filter in `cmp.Diff` as the docs say 

> FilterValues returns a new Option where opt is only evaluated if filter f, which is a function of the form "func(T, T) bool", returns true for the current pair of values being compared.

Am I missing something?

**Comment by dsnet** [comment]
The `FilterValues` is only applied to the last step in the path. In this case, the `MyStruct.MyField` step is a `string`, so you'd [need something like](https://go.dev/play/p/wUAtuNi4tGi):
```go
filter := cmp.FilterValues(
	func(x, y string) bool {
		return true
	},
	cmpopts.IgnoreFields(MyStruct{}, "MyField"),
)
```
However, this seems silly since we already know that the `MyStruct.MyField` type is a `string`.

If you're trying filter based on some other field within `MyField`, you'll [need to do something like](https://go.dev/play/p/-wYzGLHw5lf):
```go
filter := cmp.FilterPath(
	func(p cmp.Path) bool {
		ps := p.Index(-2) // -1 would be for MyStruct.MyField, -2 would be MyStruct itself
		if ps.Type() == reflect.TypeOf(MyStruct{}) {
			vx, vy := ps.Values()
			return vx.Interface().(MyStruct).OtherField > 0 && vy.Interface().(MyStruct).OtherField > 0
		}
		return true
	},
	cmpopts.IgnoreFields(MyStruct{},
		"MyField",
	),
)
```

**Comment by ryannealmes** [comment]
Thanks so much for the quick response. FilterPath was what I needed!

**Comment by pcj** [comment]
```go
filter := cmp.FilterValues(
	func(x, y string) bool {
		return true
	},
	cmpopts.IgnoreFields(MyStruct{}, "MyField"),
)
```

This is what I was looking for.  Thanks @dsnet
