### ISSUE TITLE
If x is nil, it is judged to be equal, how to set it

### ISSUE THREAD

**Issue by WanXinTao** [google/go-cmp#296]
I want to customize a comparison logic, such as comparing x and y, if x is nil, then I directly think this comparison is true, if both x and y are not nil, then compare the value specifically, x, y may be a complex model, How should I set filter func or ignore func?

**Comment by WanXinTao** [comment]
I customized a cmp.FilterValues method, but an error is reported, indicating that symmetry must be satisfied

**Comment by WanXinTao** [comment]
@dsnet

**Comment by dsnet** [comment]
The main requirement for `func(T, T) bool` functions is that they must be symmetric.

Something like the following seems to satisfy what you're asking for:
```go
cmp.FilterValues(func(x, y *T) bool {
    if x == nil || y == nil {
        return true
    }
    return false
}, cmp.Ignore())
```

**Comment by WanXinTao** [comment]
您好，感谢您给我来信，您的邮件我已收到。Thanks

**Comment by dsnet** [comment]
The entire `cmp` package is built upon the assumption of symmetric `func(T, T) bool` functions. Fundamentally what you want cannot be accomplished by this package.

**Comment by dsnet** [comment]
Closing as there's nothing to do here.
