### ISSUE TITLE
Unexpected behavior when using the EquateEmpty and IgnoreMapEntries options together with a nil map

### ISSUE THREAD

**Issue by Miciah** [google/go-cmp#298]
I want to compare two `map[string]string` values, I want to include only map entries with certain keys and ignore all other map entries, and I want to treat nil and empty as equal.  I tried to do this using go-cmp and its `EquateEmpty` and `IgnoreMapEntries` options.  The `IgnoreMapEntries` option works as expected—the following code produces the expected output: 

```go
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"

	"k8s.io/apimachinery/pkg/util/sets"
)

func main() {
	s := sets.NewString("foo")
	m1 := map[string]string{"baz": "bar"}
	m2 := map[string]string{}
	co := []cmp.Option{
		cmpopts.EquateEmpty(),
		cmpopts.IgnoreMapEntries(func(k, _ string) bool {
			return !s.Has(k)
		}),
	}
	fmt.Println(m2, m1, cmp.Equal(m2, m1, co...))
}
```
https://go.dev/play/p/6JTarYmWI2P

Output:
```
map[] map[baz:bar] true

Program exited.
```

That is, a map that is empty and a map that is empty but for ignored map entries are equal.  But if one of the maps is nil, I get an unexpected result:

```go
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"

	"k8s.io/apimachinery/pkg/util/sets"
)

func main() {
	s := sets.NewString("foo")
	m1 := map[string]string{"baz": "bar"}
	var m2 map[string]string
	co := []cmp.Option{
		cmpopts.EquateEmpty(),
		cmpopts.IgnoreMapEntries(func(k, _ string) bool {
			return !s.Has(k)
		}),
	}
	fmt.Println(m2, m1, cmp.Equal(m2, m1, co...))
}
```
https://go.dev/play/p/Yp1MjBgOT9R

Output:
```
map[] map[baz:bar] false

Program exited.
```

The comparison found that the maps are unequal despite the `IgnoreMapEntries` (which should have filtered out all entries) and `EquateEmpty` (which should have caused the empty-but-for-ignored-map-entries map and nil map to be equal).

**Comment by neild** [comment]
`EquateEmpty` and `IgnoreMapEntries` don't compose.

`EquateEmpty` says that a nil map and an empty map equate. Since `m1` is not empty, it doesn't apply.

I believe you could get your desired behavior with something like this, which transforms `nil` `map[string]string`s into empty ones:

```
	co := []cmp.Option{
		cmp.Transformer("EmptyMaps", func(m map[string]string) map[string]string {
			if m == nil {
				return map[string]string{}
			}
			return m
		}),
		cmpopts.IgnoreMapEntries(func(k, _ string) bool {
			return k != "foo"
		}),
	}
```

**Comment by dsnet** [comment]
> EquateEmpty and IgnoreMapEntries don't compose.

To explain a little more, `IgnoreMapEntries` only marks certain map entries as being excluded for comparisons, but does not actually remove them from the map. Thus, the map is very much not empty.

What Damien proposed is one way to solve this where we transform a nil map into an empty map. The other approach would be to add a `cmpopts.ExcludeMapEntries` function that transforms a map into another map with a subset of the entries.

In some cases `Ignore` composes well with other options.
In some cases `Transform` composes well with other options.
Generally `Ignore` composes better, but not always (as you are seeing here).

**Comment by dsnet** [comment]
Closing as working-as-intended. It's a surprising edge-case, but is a natural fallout of the rules that govern comparers, ignores, and transformers.
