### ISSUE TITLE
New minor release of the library?

### ISSUE THREAD

**Issue by antoninbas** [google/go-cmp#342]
Hi,

I'm opening this issue to request a new minor release of the library (v0.6.0). The last Github release is more than 1 year old, and https://github.com/google/go-cmp/pull/340, which was merged recently, is useful to compare the `netip` types. Thanks!

**Comment by dsnet** [comment]
@neild, you okay with me cutting a release?

**Comment by dsnet** [comment]
Since this includes new API, it would be a minor version bump to v0.6.0

**Comment by dsnet** [comment]
Done: https://github.com/google/go-cmp/releases/tag/v0.6.0
