### ISSUE TITLE
IgnoreFields and nested struct

### ISSUE THREAD

**Issue by kotyara85** [google/go-cmp#346]
Hey there,
So I have this struct

```
type File struct {
Sources []*Source `json:"sources"`
}


type Source struct {
 UID string `json:"uid"
}
```

I need to ignore UID as it's dynamically generated

```
cmp.Equal(c.response, response, cmpopts.IgnoreFields(File{}, "UID"))
```

Is not doing anything. Is there a way to achieve this with this package?

Thanks!

**Comment by dsnet** [comment]
Don't you mean `cmpopts.IgnoreFields(Source, "UID)`? as the "UID" field is declared on the `Source` type rather than the `File` type?

**Comment by dsnet** [comment]
Closing as there is nothing actionable here. Feel free to comment with an update and we can reopen.
