### ISSUE TITLE
Package Name Mismatches

### ISSUE THREAD

**Issue by pcfreak30** [google/go-cmp#349]
I find this odd since it seems to have been this way for a while, but Go has issues fetching the package since the `go.mod` name `go-cmp` and the actual name `cmp` aren't the same, forcing you to probably need to fork.

**Comment by neild** [comment]
I don't understand the report here. What names aren't the same? What do you mean by "need to fork"?

**Comment by pcfreak30** [comment]
Thanks, it's the 1st time I've seen this, and I already made my version fixing it based on my experience. I will see if I can get it properly working and delete my fork if so.

**Comment by neild** [comment]
Thanks. I don't believe there's any issue here. The package name is `github.com/google/go-cmp/cmp`.
