### ISSUE TITLE
Pointers as Map index keys are not respected as equal

### ISSUE THREAD

**Issue by Whoaa512** [google/go-cmp#362]
I've got a map of pointers to structs in a legacy code base and I'm unable to cleanly diff them b/c the compare pointers is not run on the keys

https://go.dev/play/p/yXCZ3SAZFj_R

**Comment by Whoaa512** [comment]
Ah I was able to workaround this with a custom compare

```go
package main

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
)

type Foo struct {
	Mapping map[*Bar]string
}

type Bar struct {
	Value int
}

func main() {
	fmt.Println("Hello, playground")

	bar1 := &Bar{Value: 1}
	bar2 := &Bar{Value: 1}

	want := &Foo{map[*Bar]string{bar1: "a"}}
	got := &Foo{map[*Bar]string{bar2: "a"}}

	// Define a custom comparator for Bar pointers
	barLess := func(a, b *Bar) bool {
		return a.Value < b.Value
	}

	// Create a custom option for comparing Foo structs
	opt := cmp.Comparer(func(x, y Foo) bool {
		return cmp.Equal(x.Mapping, y.Mapping, cmp.SortMaps(barLess))
	})

	diff := cmp.Diff(got, want, opt)
	fmt.Println(diff)
}
```

And further if I needed to compare a more complex struct, I could call `cmp.Equal` within my custom map sort func

**Comment by dsnet** [comment]
Hi, I'm glad you figured it out with the use of `cmpopts.SortMaps`.

I suspect you can simplify this and just pass in `cmpopts.SortMaps` directly without wrapping it within a `cmp.Comparer`.

**Comment by Whoaa512** [comment]
Yup that's what I ended up with after some more playing with it. The above was what Claude gave me to start with
