### ISSUE TITLE
Optimizing Struct Field Alignment

### ISSUE THREAD

**Issue by ZuhairORZaki** [google/go-cmp#369]
# Overview

In file: [report_reflect.go](https://github.com/google/go-cmp/blob/v0.6.0/cmp/report_reflect.go#L26), the fields of the `formatValueOptions` struct are organized in a way that takes more memory. The fields of the struct can be sorted in a way that takes less memory than the initial alignment.

```go
type formatValueOptions struct {
	// AvoidStringer controls whether to avoid calling custom stringer
	// methods like error.Error or fmt.Stringer.String.
	AvoidStringer bool

	// PrintAddresses controls whether to print the address of all pointers,
	// slice elements, and maps.
	PrintAddresses bool

	// QualifiedNames controls whether FormatType uses the fully qualified name
	// (including the full package path as opposed to just the package name).
	QualifiedNames bool

	// VerbosityLevel controls the amount of output to produce.
	// A higher value produces more output. A value of zero or lower produces
	// no output (represented using an ellipsis).
	// If LimitVerbosity is false, then the level is treated as infinite.
	VerbosityLevel int

	// LimitVerbosity specifies that formatting should respect VerbosityLevel.
	LimitVerbosity bool
}
```

For the above alignment, the size of the struct is 24 bytes (for 64-bit systems). It can be reduced to 16 bytes by aligning the fields as follows:

```go
type formatValueOptions struct {
	// VerbosityLevel controls the amount of output to produce.
	// A higher value produces more output. A value of zero or lower produces
	// no output (represented using an ellipsis).
	// If LimitVerbosity is false, then the level is treated as infinite.
	VerbosityLevel int

	// AvoidStringer controls whether to avoid calling custom stringer
	// methods like error.Error or fmt.Stringer.String.
	AvoidStringer bool

	// PrintAddresses controls whether to print the address of all pointers,
	// slice elements, and maps.
	PrintAddresses bool

	// QualifiedNames controls whether FormatType uses the fully qualified name
	// (including the full package path as opposed to just the package name).
	QualifiedNames bool

	// LimitVerbosity specifies that formatting should respect VerbosityLevel.
	LimitVerbosity bool
}
```

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by neild** [comment]
Thanks, but no thanks. Outside of some very narrow performance-critical scenarios, we prefer code clarity over optimizing away every possible byte.

It's possible that a future version of the Go compiler will automatically reorder fields for optimal packing.
