### ISSUE TITLE
diff output with multiple differences is unhelpful

### ISSUE THREAD

**Issue by rogpeppe** [google/go-cmp#64]
I ran across this recently when using cmp to test differences in unmarshal results.
One unmarshaler was unmarshaling numbers as floats, the other as ints, but the
Diff result didn't make it at all clear what the difference was.

Example code:

	package main
	
	import (
		"fmt"
	
		"github.com/google/go-cmp/cmp"
	)
	
	func main() {
		x := []interface{}{map[string]interface{}{"avg": 0.278, "hr": 65, "name": "Mark McGwire"}, map[string]interface{}{"avg": 0.288, "hr": 63, "name": "Sammy Sosa"}}
		y := []interface{}{map[string]interface{}{"avg": 0.278, "hr": 65.0, "name": "Mark McGwire"}, map[string]interface{}{"avg": 0.288, "hr": 63.0, "name": "Sammy Sosa"}}
	
		diff := cmp.Diff(x, y)
		fmt.Printf("diff: %s\n", diff)
	}

This prints:

	diff: root:
		-: []interface {}{map[string]interface {}{"avg": 0.278, "hr": 65, "name": "Mark McGwire"}, map[string]interface {}{"avg": 0.288, "hr": 63, "name": "Sammy Sosa"}}
		+: []interface {}{map[string]interface {}{"avg": 0.278, "hr": 65, "name": "Mark McGwire"}, map[string]interface {}{"avg": 0.288, "hr": 63, "name": "Sammy Sosa"}}

Note that both lines are identical.

**Comment by dsnet** [comment]
The tip version of `cmp` does avoid shoving this all on one line, but still suffers from not printing the type:
```
root[0]["hr"]:
	-: 65
	+: 65
root[1]["hr"]:
	-: 63
	+: 63
```
