### ISSUE TITLE
Filtering struct field by name

### ISSUE THREAD

**Issue by kaskavalci** [google/go-cmp#69]
Is it possible to filter a struct field by its name? Inside `FilterValues` we can only access to the variable itself, and reflect does not know about the variable name.

**Comment by dsnet** [comment]
If you're trying to ignore a field by name, you could use [cmpopts.IgnoreFields](https://godoc.org/github.com/google/go-cmp/cmp/cmpopts). If you want to filter for fields and do something other than ignore, you'll need to look at the implementation for IgnoreFields and do something similar.

**Comment by kaskavalci** [comment]
I didn't see the whole `cmpopts` package. Thanks for the info.
