### ISSUE TITLE
question: policy/schedule for tagging a git release

### ISSUE THREAD

**Issue by dnephin** [google/go-cmp#72]
Related to #37 , apologies if this is documented somewhere and I missed it.

I'm looking forward to getting the changes from #45 into a tagged git release so that I can use a `dep` constraint other than `branch = master`, which is not great for consumers of my package.

Do you have a policy for when to tag a new release, based on time or the number/size of changes since the last tagged release?

It has been just over 6 months from `0.1` so I'm wondering if you'd consider a `0.2`.

Thanks for this package!

**Comment by dsnet** [comment]
The `cmp` project isn't one that I foresee undergoing continual development. There are few features to add here and there, but I don't think a release cycle every N months makes sense. A release every N commits makes more sense, but isn't the best policy either. Ideally, we tag it based upon when major features or bug fixes are done. Also, I would like to see dependency management become an official feature of Go before we formalize our own release "schedule".

For the time being we'll hold to an informal policy of tagging a new release based upon a user request (as you are doing) or when we believe sufficient features has accumulated to justify a new tag. I'll tag a new release tomorrow when I'm back in the office.

**Comment by dsnet** [comment]
Done.

https://github.com/google/go-cmp/releases/tag/v0.2.0

**Comment by dnephin** [comment]
Awesome, thank you!
