### ISSUE TITLE
cmp.Equal doesn't work with big.Int out of the box

### ISSUE THREAD

**Issue by LMMilewski** [google/go-cmp#90]
It would be nice if types like big.Int worked out of the box.
big.Int doesn't provide Equal method. It has [Cmp](https://godoc.org/math/big#Int.Cmp) though.

I don't know how common types with Cmp but no Equal are. If they're common then we could consider teaching cmp about Cmp methods. If they're not then perhaps we could make math/big provide Equal methods.

In general, it would be nice if cmp just worked with as many stdlib types as possible.

Having simple cmp.Equal work with more types would be nice but isn't a big deal either.

**Comment by nhooyr** [comment]
Related https://github.com/google/go-cmp/issues/89

**Comment by dsnet** [comment]
At this point in time, I don't think we can change which methods `cmp` automatically looks for without breaking backwards compatibility. The workaround is to just provide a `Comparer` that works on an
```interface{ Cmp() int }```.
